### ISSUE TITLE
Incluir opção "excluir link do registro"

### ISSUE THREAD

**Issue by suelisuga** [bireme/social-checklinks#1]
Solicitamos que no sistema Social Check Links seja possível que o documentalista possa indicar qual procedimento FIR deve tomar:

Excluir link do registro se a revista nao estiver mais online mas tiver coleção impressa em alguma biblioteca.

Atenciosamente,

Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by heitorbarbieri** [comment]
Com a opção "Excluir o campo do documento associado a este link " marcada, o sistema apaga o campo contendo a url do registro na base correspondente e gera uma linha no relatório indicando a ação realizada assim como informações de identficador de registro, url, qual usuario e centro colaborador associados ao link. 
O relatório é automaticamente transferido para o mesmo lugar de onde a base de dados atualizada é normalmente transferida.
