### ISSUE TITLE
Incluir opção "excluir registro"

### ISSUE THREAD

**Issue by suelisuga** [bireme/social-checklinks#2]
Solicitamos que no sistema Social Check Links seja possível que o documentalista possa indicar qual procedimento FIR deve tomar após links corrigidos:

Excluir registro se a revista nao estiver mais online e não tiver coleção impressa em nenhuma biblioteca da rede.

Atenciosamente,

Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by heitorbarbieri** [comment]
Com a opção "Excluir o documento associado a este link " marcada, o sistema apaga o registro na base correspondente e gera uma linha no relatório indicando a ação realizada assim como informações de identficador de registro, url, qual usuario e centro colaborador associados ao link.
O relatório é automaticamente transferido para o mesmo lugar de onde a base de dados atualizada é normalmente transferida.
