### ISSUE TITLE
Implantar conferência de links quebrados da semana com lista de links já corrigidos no sistema

### ISSUE THREAD

**Issue by suelisuga** [bireme/social-checklinks#3]
Solicito que a lista de links quebrados gerados na semana seja conferida com os links já corrigidos dentro do sistema.

Se nao for possivel conferir com todos os links já corrigidos, definir tempo de pelo menos 3 semanas para não reapresentação.

Justificativa: grande volume de links quebrados corrigidos estão sendo reapresentados na semana seguinte à correção, gerando a necessidade de iniciar o trabalho a partir da sétima ou oitava página de links quebrados.

De modo auxiliar, um controle em tabela excel com ID e ação realizada tem sido mantido pelos documentalistas para garantir que nao haja duplicação ou retrabalho de conferencia de links já corrigidos.

Obrigada

Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by heitorbarbieri** [comment]
Agora, links que foram corrigidos  em um período de até 60 dias não reaparecem no Social Check Links como links quebrados novamente. 

Acrescentada também a opção " Excluir este link de verificações futuras " que se marcada elimina qualquer checagem futura do mesmo link. Tal link assim como informações associadas são adicionados ao relatório que é enviado juntamente com a base de dados para o servidor destino.
