### ISSUE TITLE
Sistema não aceita link para correção

### ISSUE THREAD

**Issue by suelisuga** [bireme/social-checklinks#4]
Sistema não aceita link informado para correção e informa: "Más notícias! Link quebrado. Tente editar e gravar novamente". Porém o link está funcionando e isso impossibilita a correção desse registro.

Exemplos: IDs 726007, 675029,527925

Abs,

Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by heitorbarbieri** [comment]
O sistema de checagem de links foi substituído e aprimorado de forma a sempre apresentar os mesmos códigos de retorno dos aplicativos curl e wget do Linux. Espera-se que com isso o problema acima citado tenha sido solucionado.
